#!/bin/bash

# todo: add checks for stuff lol

# initialize venv, update pip
python -m venv .venv
.venv/bin/python -m pip install --upgrade pip > /dev/null
# install & run black
.venv/bin/pip install black > /dev/null
.venv/bin/black . --include '(fusecore/.+\.py)$' -t py313 -l 80